### ISSUE TITLE
Question: how to manage alembic autogenerate in multi-module project structure

### ISSUE THREAD

**Issue by devjourney24** [zhanymkanov/fastapi_production_template#3]
Hi,
Thank you for your great work!

Something is unclear for me according to "FastAPI Best Practices" and this repo.

If this repository would have the same multi-module structure (src/auth/models.py, src/posts/models.py), the alembic will not see these models during the autogenerate, because we need import Base and all models we want to track somewhere in one place.

How do you handle this?

Is the alembic/env.py the best place to do these imports?

For example:
```
from src.models import Base  # noqa
from src.auth.models import User # noqa
from src.posts.models import Post # noqa

target_metadata = Base.metadata
```

I think explicit imports in env.py is not a bad idea, because we can control which models alembic will be tracking.

But what is the best practice?

**Comment by zhanymkanov** [comment]
Hi,

I think with SQLAlchemy ORM and a common base model, alembic is able to see the common metadata for all models that inherit from that class, so that's not a problem (at least when I was working with ORM a long time ago).

For the SQLAlchemy Core and db table definitions, I do a controversial, yet simple trick - put all Table schemas in one file - `src.database` - that way alembic is able to see changes. Then, each package's service just imports the table schema and works with it (you can see examples in the `src.auth.service`). 

Putting all the table schemas in one file sounds smelly, but it worked for us and we didn't even notice it while having a medium-sized codebase with several dozens of tables (50-60 Table objects). DB tables didn't change frequently, but the services around them did.

Importing all the models in `env.py` sounds smart, but having an obligation to do it every time you add a new table feels like a burden to me.

**Comment by ntoskrn** [comment]
Hey,

I did this script (in alembic/env.py), altough it's hacky it may help you.
```py
# ...
import os
# ...

for root, dirs, files in os.walk("src"):
    for file in files:
        if file == "models.py":
            path = os.path.join(root, file).replace(os.sep, ".")[:-3]
            module = __import__(path)

# ...
# this is the Alembic Config object, which provides
# ...
```
